### ISSUE TITLE
Initial porting of code from cove repo

### ISSUE THREAD

**Issue by robredpath** [open-contracting/cove-ocds#1]

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Refactor OCDS-specific code into a new application](https://trello.com/c/6SyOfmT6/49-refactor-ocds-specific-code-into-a-new-application)

**Comment by rhiaro** [comment]
Initial porting done, master now contains a standalone OCDS DRT.
