### ISSUE TITLE
Flattening record packages

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/cove-ocds#117]
Some quick notes from a discussion with @kindly  on this today:

The primary use case we have in mind is publishers sharing draft data with the helpdesk in record package format and helpdesk analysts wanting to flatten this to help give feedback (e.g. it's easier to check all the values of a given field by looking at a spreadsheet than by reviewing a JSON file).

Records have the following components:
 * Compiled release - easiest to flatten, using existing flatten-tool functionality. could include in minimal version of record package flattening
 * Releases list, which can be either linked releases or flattened releases. Key issue is the field is `oneOf` and it isn't possible to definitely tell which has been provided. Also the list could be mixed. Would require more work.
    * Linked releases - assume we won't fetch full releases for flattening, Q: would flattening the list of linked releases (url, date and tag) be useful?
    * Embedded releases - would need to combine the release lists from all records into one list - not sure where this functionality would sit between CoVE and flatten-tool. Could require lots of work.
 * Versioned release - we don't have approach to flattening this and it is very rarely used by published, would leave out of functionality for now

We also discussed whether compiled and embedded releases should be flattened into the same spreadsheet.

* Flattening to separate spreadsheets would be easier to implement and it would be easier to use for users who just wanted to work with one or the other (no filtering out would be required). 
* Flattening to one spreadsheet would be harder to implement but it would make it easier for users who wanted to do analysis across compiled and individual releases (we don't have a specific use case for that in mind).

We also discussed whether this would sit better in CoVE/flatten-tool or OCDSKit/-web (possibly via the tabulate command supporting a spreadsheet output).

Seeking feedback from @yolile @romifz @jpmckinney @mrshll1001@pindec and others on:

* How important is this for the helpdesk
* Other use cases for flattening record packages
* Views on which elements of records are important to flatten
* Flattening records into one or multiple spreadsheets
* Where this functionality belongs

**Comment by jpmckinney** [comment]
This feature will be removed, based on user research. There is not much evidence of users downloading spreadsheets.
