### ISSUE TITLE
Include package metadata in 'fields that are empty or contain only whitespaces' check

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/cove-ocds#121]
It looks like this check currently only looks at the release, not the package metadata, at least a blank string `publisher/scheme` is not reported by the check.

The check should be carried out on both the package metadata and the contents of the package.

I'm not sure how this is implemented, so worth checking if this issue is specific to this check or whether it applies to the way additional checks work in general.

**Comment by jpmckinney** [comment]
I'm not sure if lib-cove-ocds reports these and they just aren't being displayed, or if we need to edit lib-cove-ocds (in which case we can transfer the issue there).

**Comment by jpmckinney** [comment]
Package metadata will be deprecated in OCDS 1.2, so I'll close this as "wontfix".
