### ISSUE TITLE
Remove duplication of validation messages from within oneOf

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/cove-ocds#126]
Introduced as part of https://github.com/OpenDataServices/cove/issues/895 when we replaced the monolithic `oneOf` validation messages with the individual messages for each subschema.

Errors about `date` and `tag` being required can come from either subschema, and are repeated for each.

This is only a problem for files that have a mix of assumed embedded and linked releases for different records.

**Comment by jpmckinney** [comment]
> This is only a problem for files that have a mix of assumed embedded and linked releases for different records.

This very rarely (if ever) occurs, so okay to close.
