### ISSUE TITLE
Error with validation checks for Release IDs

### ISSUE THREAD

**Issue by mrshll1001** [open-contracting/cove-ocds#127]
In OCDS the guidance for release IDs is given [as follows](https://standard.open-contracting.org/latest/en/schema/identifiers/#release-id):

> A release identifier must be unique within the scope of the contracting process of which it is a part. In other words, across all OCDS releases with the same ocid value, each release identifier refers to exactly one release; no two releases use the same release identifier.
>
>A release identifier must also be consistent within this scope. For example, if the id of a release is “12345” in one release package, then the id of the same release in another release package must also be “12345”.

This means two releases may have the same release id *if* they are under different contracting processes (OCIDs) and still be valid. In [this gist](https://gist.github.com/mrshll1001/2f8ff5c8e2f687a547eb75b30b5eebbe) there are 11 releases under 11 different OCIDs, which all happen to share a release ID. The expected behaviour is that the release ids are not flagged as invalid however CoVE is flagging this as a problem.

**Comment by jpmckinney** [comment]
@Bjwebb To understand the state of the issue: Has the check been updated in lib-cove-ocds, and now we're just discussing how it's reported, or does that first step still need to be done? (I can then rename and/or transfer the issue.)

**Comment by Bjwebb** [comment]
I've made the change on a branch, but haven't had chance to look at tests.

https://github.com/OpenDataServices/lib-cove/compare/cove-1253-multiple-ids
https://github.com/open-contracting/lib-cove-ocds/compare/cove-1253-multiple-ids

**Comment by Bjwebb** [comment]
There's now lib-cove and lib-cove-ocds PRs for this work, with tests:
* https://github.com/OpenDataServices/lib-cove/pull/85
* https://github.com/open-contracting/lib-cove-ocds/pull/91
