### ISSUE TITLE
Relax deletion schedule

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/cove-ocds#142]
e.g. to 90 days. It's not uncommon for results to expire before the Helpdesk has finished going through them with a publisher.

From [this report](https://docs.google.com/document/d/1M2Y-aK3-RzbzziXEOEInYDaCjWqV-Ak7mZEOm9Ut34E/edit):

> increase the prominence of the deletion notice, so that people understand that results will only be available for a limited time.

**Comment by Bjwebb** [comment]
This is now live on cove-ocds with 90 day expiry. @jpmckinney I'm assuming we want the same for cove-oc4ids?

**Comment by jpmckinney** [comment]
Yes, that seems reasonable, though we can just create an issue for it.
