### ISSUE TITLE
"Codelist Errors" > Codelist links currently break: okfnlabs have archived their datapipes CSV viewer 

### ISSUE THREAD

**Issue by pindec** [open-contracting/cove-ocds#152]
Links to view codelist csvs that used datapipes now break.

[DRT output on example data demonstrating the issue](https://standard.open-contracting.org/review/data/48cc24ca-08f1-49e7-b7dd-381421c40066).

Link to view releaseTag.csv is http://datapipes.okfnlabs.org/csv/html/?url=https://raw.githubusercontent.com/open-contracting/standard/1.1/schema/codelists/releaseTag.csv which redirects to https://datapipes.datopian.com/ (an advisory page saying datapipes has been archived).

Note that the link to view the releaseTag codelist in the Structural Errors box links directly to the codelist in standard docs: https://standard.open-contracting.org/1.1/en/schema/codelists/#release-tag.

**Comment by pindec** [comment]
Ah, source is [lib-cove-web](https://github.com/OpenDataServices/lib-cove-web/blob/c242d507da948059520a97248041035f18a04e21/cove/templates/additional_codelist_values.html#L18).

**Comment by jpmckinney** [comment]
Fixed in OpenDataServices/lib-cove-web#74
