### ISSUE TITLE
Docker container implementation

### ISSUE THREAD

**Issue by saboyle** [open-contracting/cove-ocds#164]
Using docker may ease running and deploying the tool.  (Created as an exercise and sharing in case it's of any use.)

Initial exploration / notes:
-------------------------
Example Dockerfile and docker-compose files below (seems to work ok but needs more testing).  

Both should be created in the root of the repo after cloning.

Dockerfile
````Docker
# Based on -> https://blog.bitsacm.in/django-on-docker/

# Use the official Python image from the Docker Hub
FROM python:3.8.2

# These two environment variables prevent __pycache__/ files.
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

# Make a new directory to put our code in.
RUN mkdir /code

# Change the working directory.
# Every command after this will be run from the /code directory.
WORKDIR /code

# Copy the requirements.txt file.
COPY requirements.txt /code/

# Upgrade pip
RUN pip install --upgrade pip

# Install the requirements.
RUN pip install -r requirements.txt

# Copy the rest of the code.
COPY .. /code/

RUN apt update
RUN apt install gettext -y

RUN python manage.py migrate
RUN python manage.py compilemessages
````

docker-compose.yaml file
````Docker
version: '3'

services:
  web:
    container_name: cove_project
    build: .
    image: cove_ocds/drt:v1
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
````

To build the docker container ...
````sh
docker-compose build
````
To run the docker container ...
````sh
docker-compose up
````
To verify open a browser and goto localhost:8000.

The attached files will build a docker image: *cove_ocds/drt:v1*

**Comment by jpmckinney** [comment]
Thanks, @saboyle! We don't currently use Docker for this app, which is deployed using SaltStack, but these are useful notes if we change our deployment in the future.

**Comment by saboyle** [comment]
No worries @jpmckinney. btw it should be easy to (auto) convert the above to run in kubernetes too if needed.
