### ISSUE TITLE
Write overview documentation

### ISSUE THREAD

**Issue by rhiaro** [open-contracting/cove-ocds#2]
> In this first iteration, this documentation should cover information that is unique to the DRT (i.e. we should assume that the developer knows Python, Django, JSON Schema, OCDS, etc. which are not unique to the DRT). It should cover the information that developers newly working on the DRT would be given, with respect to the responsibilities of each component (lib-cove-ocds, lib-cove, cove-ocds, cove), for example.

Related reading:

* [General CoVE docs](https://cove.readthedocs.io/en/latest/)
* [OCDS tools](https://standard.open-contracting.org/latest/en/support/tools/)
* [ocdskit](https://ocdskit.readthedocs.io/en/latest/)
* [lib-cove-ocds](https://github.com/open-contracting/lib-cove-ocds)

Possible contents:

* Internal architecture of cove-ocds (where to find code for what)
* Connection with external libs
* How to add an additional check
* Translations
* The CLI
* Template structure
* Something about extensions

**Comment by rhiaro** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Write overview documentation for the DRT](https://trello.com/c/Y07UW30f/15-write-overview-documentation-for-the-drt)

**Comment by ColinMaudry** [comment]
Chapter 1: what does DRT stand for?

:wink:

**Comment by jpmckinney** [comment]
Some notes by @Bjwebb on:

* How to add headlines
* How to modify validation error messaging

https://docs.google.com/document/d/1EER_GjXi7F0SPZ_Mra9JuQBY5JxU0NGRSS9mYzB4guU/edit
