### ISSUE TITLE
Create repository for test data

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/cove-ocds#37]
https://github.com/open-contracting/cove-ocds/pull/35#issuecomment-624563899 has links to test data and scripts to generate data.

If the data can't be made public, we should create a private repository to put the data and scripts.

cc @Bjwebb

**Comment by Bjwebb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Quick fixes for large files](https://trello.com/c/pZJldiNG/70-quick-fixes-for-large-files)

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Check test data into a new repo (private if necessary)](https://trello.com/c/wQ2W8uY6/77-check-test-data-into-a-new-repo-private-if-necessary)

**Comment by Bjwebb** [comment]
@jpmckinney  How does https://github.com/open-contracting/sample-data-private look?

If that's okay, I'll update that PR to link to it.

**Comment by jpmckinney** [comment]
I suggest moving the two JSON files into a `data` directory, so that if/when we add more private sample data, we don't end up with a cluttered root directory. Otherwise, looks good!

**Comment by Bjwebb** [comment]
Files moved, and links added from PR.
