### ISSUE TITLE
Truncate check results

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/cove-ocds#59]
Follow-up to https://github.com/open-contracting/cove-ocds/issues/31, which yielded https://github.com/open-contracting/cove-ocds/pull/35.

## Problem

Large, invalid files yield very large response sizes (performance), and more information than is useful (UX), e.g. a list of 42,000 invalid entries for one error type.

File|Valid?|File Size|Response size before PR|Response size after releases table PR https://github.com/open-contracting/cove-ocds/pull/35
---|---|---|---|---
repeated_errors_repeated.json (not public data)|Invalid|359MB|65.8 MB|27.32 MB
[badfile_repeated.json](http://temp.dev3.default.opendataservices.uk0.bigv.io/ocds_sample_data/badfile_repeated.json) ([script to generate](https://gist.github.com/Bjwebb/2507c57e5ce9fea9a833135d2142a671))|Invalid|341MB|174.18 MB|150 MB

Test files are now here: https://github.com/open-contracting/sample-data-private/tree/master/data

## Solution

I think we can have a configurable setting to limit the number of results returned.

To address performance issues, we can set a high limit that still exceeds usefulness, like 1000.

To address usability issues, we can have a smaller number like 100. We'll want to randomize the results returned, so that we're not simply reporting e.g. the first 100 errors all caused by old data and none of the errors caused by newer data (publishers who are only making improvements to new data are likely to ignore the results if they only seem to pertain to old data).

**Comment by Bjwebb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Limit JSON paths shown for validation errors if there are lots](https://trello.com/c/9ZHuauJF/91-limit-json-paths-shown-for-validation-errors-if-there-are-lots)

**Comment by Bjwebb** [comment]
Truncating to 1000 looks good in terms of limiting the page size:

File|Valid?|File Size|Response size before PR|Response size after releases table PR https://github.com/open-contracting/cove-ocds/pull/35|Response size after truncating errors to 1000
---|---|---|---|---|---
repeated_errors_repeated.json (not public data)|Invalid|359MB|65.8 MB|27.32 MB|5MB
[badfile_repeated.json](http://temp.dev3.default.opendataservices.uk0.bigv.io/ocds_sample_data/badfile_repeated.json) ([script to generate](https://gist.github.com/Bjwebb/2507c57e5ce9fea9a833135d2142a671))|Invalid|341MB|174.18 MB|150 MB|30.7MB

**Comment by jpmckinney** [comment]
Great!

**Comment by Bjwebb** [comment]
This is live now.

Currently the live deploy uses the default of a 1000 limit and no randomisation [[demo]](https://standard.open-contracting.org/review/?source_url=https://raw.githubusercontent.com/open-contracting/cove-ocds/4aa22a203ce943b98413e96705c9dc16cfb9e843/cove_ocds/fixtures/1001_empty_releases.json)
I've set the dev deploy with a 100 limit and randomisation for comparison [[demo]](https://cove.dev1.cove.opencontracting.uk0.bigv.io/review/?source_url=https://raw.githubusercontent.com/open-contracting/cove-ocds/4aa22a203ce943b98413e96705c9dc16cfb9e843/cove_ocds/fixtures/1001_empty_releases.json)

@jpmckinney Do you want to take a look at these, and decide what settings we want?

**Comment by jpmckinney** [comment]
@Bjwebb I think 100 with randomization is better. Happy for an analyst to have a say as well!

**Comment by pindec** [comment]
I appreciate the argument for randomisation re new/old data, but randomisation may be problematic if you are trying to verify whether your latest fix has worked, and the specific item you are working on isn't consistently reported on. I guess publishers could subset their data to check a specific fix now reports OK.

Also, it means the reporting becomes inconsistent with the "location of first 3 errors" which I assume is source release array location asc. 

Ideally we would expose the selection-of-n-top-results-method to the user, with the default being source release array location asc, with an option to do desc, or randomise, and/or select _n_ of the results.

In terms of how many fields are reported in the modal, ideally there would be a downloadable csv of the data. Erring on the side of more info would be good (especially for the has-my-specific-fix-worked case above). However, copy and paste of those fields in the modal seems to grab info from the whole page, so maybe in the absence of a download, 100 is a bit more usable than 1000.

**Comment by jpmckinney** [comment]
> I appreciate the argument for randomisation re new/old data, but randomisation may be problematic if you are trying to verify whether your latest fix has worked, and the specific item you are working on isn't consistently reported on. I guess publishers could subset their data to check a specific fix now reports OK.

Good point – do we know if people are using the tool in that way? Also, does the interface report the (non-truncated) total number of occurrences of the error, in which case the publisher knows if they're making progress by checking the number of occurrences?

> Also, it means the reporting becomes inconsistent with the "location of first 3 errors" which I assume is source release array location asc.

Good catch – we should update this label.

> Ideally we would expose the selection-of-n-top-results-method to the user, with the default being source release array location asc, with an option to do desc, or randomise, and/or select _n_ of the results.

I think that's providing too many options to the user. It's better to determine and then provide a single, best option. Let's start with no randomization – this also makes it clearer to the user if an error is systematic (e.g. they see that there's an error in releases/0, releases/1, releases/2, etc.).

> In terms of how many fields are reported in the modal, ideally there would be a downloadable csv of the data. Erring on the side of more info would be good (especially for the has-my-specific-fix-worked case above). However, copy and paste of those fields in the modal seems to grab info from the whole page, so maybe in the absence of a download, 100 is a bit more usable than 1000.

We can option a new issue about CSV downloads. However, I haven't heard demand from users yet. For the helpdesk, we use Colab and Pelican instead, from which we can get downloads.

**Comment by pindec** [comment]
> Good point – do we know if people are using the tool in that way? 

Not directly, but my understanding is the key use case is fast iteration around draft data when preparing to publish or data samples post-publication to check they are publishing correctly which presumably includes a test-fix-test cycle.

> Also, does the interface report the (non-truncated) total number of occurrences of the error, in which case the publisher knows if they're making progress by checking the number of occurrences?

Yes, I think the interface should report the non-truncated total to aid debugging.

> We can create a new issue about CSV downloads. However, I haven't heard demand from users yet. For the helpdesk, we use Colab and Pelican instead, from which we can get downloads/exports.

Sure. Since the use case about csv downloads is unknown, should we instead/also open an issue to update the DRT instructions /more information section to flag up the key DRT use case and alternative validation options for publishers who want to continuously validate and/or validate large amounts of data e.g. [following this blog post](https://www.open-contracting.org/2018/05/09/check-ocds-data-validates/) but updating it (e.g. hosted jOCDS seems to be missing)? 

Is there also another potential issue around doing some additional work to make the output of [ocdskit-validate](https://ocdskit.readthedocs.io/en/latest/cli/ocds.html#validate) and/or [lib-cove](https://github.com/open-contracting/lib-cove-ocds) a bit more user-friendly to support publishers wanting to use those options directly, and/or create a shareable notebook to do so? ocdskit-validate output doesn't seem to give the same locations info, and lib-cove output may need some processing to make it more user-friendly.

**Comment by jpmckinney** [comment]
I think we're agreed on 100 with no randomization.

> Sure. Since the use case about csv downloads is unknown, should we instead/also open an issue to update the DRT instructions /more information section to flag up the key DRT use case and alternative validation options for publishers who want to continuously validate and/or validate large amounts of data e.g. following this blog post but updating it (e.g. hosted jOCDS seems to be missing)?

Yes, or add a comment to #62, which has other comments about the landing page's text.

> Is there also another potential issue around doing some additional work to make the output of ocdskit-validate and/or lib-cove a bit more user-friendly to support publishers wanting to use those options directly, and/or create a shareable notebook to do so? ocdskit-validate output doesn't seem to give the same locations info, and lib-cove output may need some processing to make it more user-friendly.

Yes, please open an issue in lib-cove-ocds.

**Comment by duncandewhurst** [comment]
Looks like the live deploy now limits the output to 100 locations, so I'll close this issue.
