### ISSUE TITLE
Improved text on landing page

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/cove-ocds#62]
From https://github.com/OpenDataServices/cove-oc4ids/issues/19

The form prompts can be improved so that a first-time user knows what to do without scrolling below the fold to read the instructions, for example: "Paste an OCDS release package or record package as JSON" instead of simply "Paste". I can suggest more improvements, but I recommend that either @mrshll1001 or @pindec do a quick review to pick up these types of usability issues for first-time users.

----

Similarly, the order and flow of content below the form doesn't put the most important or relevant information first.

For example, I would at minimum swap the positions of the "Check and Review" and "About OCDS" blocks. Ideally, "About OCDS" would come after both other blocks, as it's the least relevant content; anyone arriving at the OCDS Data Review Tool is very likely to at least know what OCDS is.

The text in each box can also be clearer, simpler, more straight-forward for first-time users. As in issue description, I think others should do a first pass.

----

Noting some quick observations from Hotjar recordings. In general, drawing conclusions from recordings over a short period will be biased, as the recordings will tend to be the same user working to implement OCDS.

* Many users don't get past the first page. The common behavior is to scroll past the form, loiter around the content area, scroll further down, then back up to the content area.
  * Similar to my heuristic observations above, my interpretation is that people don't know what the tool does yet, so they don't know what the form is about and skip it. They get to the content area and scan it, but the content isn't ordered by priority (and there's a fair amount of it), so they scroll further down to scan the content there, realize that content is even less relevant, so scroll back up to read the content more closely.
* Users don't seem to know what to do with the error about not identifying a package structure.
  * We can perhaps display a JSON snippet of the skeleton of a package, to show what it should look like. We might also have a truncated (e.g. first 1000 characters) copy of their indented JSON shown side-by-side.
* One user abandoned the form.
  * Instead of just "Loading" and a spinner, we should display a message that for large inputs, the form will take some time to submit, and to please be patient.

Moved from https://github.com/OpenDataServices/cove/issues/1197

**Comment by pindec** [comment]
Additional notes from discussion in [#59](https://github.com/open-contracting/cove-ocds/issues/59#issuecomment-707640835):

Update the DRT landing page to:
1. flag up the key DRT use case (rapid testing of small amounts of sample data) 
2. flag alternative validation options for publishers who want to continuously validate and/or validate large amounts of data.

For (2):
- Based on [this blog post](https://www.open-contracting.org/2018/05/09/check-ocds-data-validates/) but updated (e.g. hosted jOCDS seems to be missing)
* And/or improved usability/documentation around using lib-cove-ocds [issue 85](https://github.com/open-contracting/lib-cove-ocds/issues/85).

**Comment by jpmckinney** [comment]
This issue is addressed in the draft wireframes for the frontend update.

**Comment by jpmckinney** [comment]
Tagging @sabahfromlondon in case anything in this issue is informative.
