### ISSUE TITLE
KFI: Include count of unique item IDs

### ISSUE THREAD

**Issue by robredpath** [open-contracting/cove-ocds#69]
Feature request from OpenDataServices/cove#263 

Original text:
> When a file containing multiple releases is validated, the total count of items and documents are shown. For clarity, could we also include the unique count of:
>
> *  items based on id
>
> By showing that we found 19 mentions of a document and 4 unique document ids, publishers can be check the release has been validated correctly.

**Comment by jpmckinney** [comment]
This feature will be removed, based on user research.
