### ISSUE TITLE
KFI: Improve documentation of results

### ISSUE THREAD

**Issue by robredpath** [open-contracting/cove-ocds#70]
Copied from https://github.com/OpenDataServices/cove/issues/263#issuecomment-522733167

KFI is an important part of how the Helpdesk supports publishers to understand their data but to an unsupported user who is still learning about the standard the terse presentation of the stats isn't helpful. 

Inline docs could be useful here. 

Original text:

> I have a great deal of difficulty understanding how each of the numbers is calculated (using the linked file as input). For example, 8 releases have an (identical) planning field, and the number is 1.

> However, I think we first need to determine how frequently this section is referenced, before investing time in improving its clarity.

**Comment by jpmckinney** [comment]
This feature will be removed, based on user research.
