### ISSUE TITLE
List fields that are present/missing compared to the schema 

### ISSUE THREAD

**Issue by robredpath** [open-contracting/cove-ocds#71]
Copied from https://github.com/OpenDataServices/cove/issues/118 

Although we provide a list of fields that are present but aren't in the schema (ie, "additional fields"), we don't provide a list of fields that are in the schema but aren't in the file, or any other way for people to discover fields that may be relevant to them from the results page. The risk, of course, is that excessive noise is generated, but some way of allowing people to see their mapping template alongside their existing coverage could help alignment.

**Comment by jpmckinney** [comment]
From document in #101:

> Coverage mapping, e.g. a visualization like a heatmap (useful to policy people deciding what to include/add); Lindsey: could alternately be done through other work on publication plan and OCDS concepts. James: Low priority until use cases for this feature are clearly articulated.

**Comment by jpmckinney** [comment]
My comment from [this report](https://docs.google.com/document/d/1M2Y-aK3-RzbzziXEOEInYDaCjWqV-Ak7mZEOm9Ut34E/edit):

> This specific use case is covered through the mapping phase (it shouldn't require a developer implementing a mapping and running the mapped data through the DRT for a government analyst to have an opportunity to say that budget data is available from the Ministry of Finance...). Otherwise, covered by Pelican and feedback reports.
>
> Also, the data that is uploaded to the DRT tends to be samples, which tend to be non-representative. For example, if the excerpt is only the most recent data, it might only include releases for tender notices, such that awards and contracts are unpopulated. In general, fields that are infrequently populated might not occur in the sample. So, the results might not be that useful.

**Comment by duncandewhurst** [comment]
Noting that, since https://github.com/OpenDataServices/lib-cove/pull/89, lib-cove produces a schema annotated with coverage statistics and https://github.com/open-contracting/cove-oc4ids/pull/104 adds a tree-view visualization of coverage.

In OC4IDS, data uploaded to the DRT is more often representative and many implementers build OC4IDS-based publication systems from scratch, rather than mapping an existing system to the schema.

**Comment by jpmckinney** [comment]
Indeed - for example, the FTS and Scotland implementations typically uploaded one notice type at a time, which was not representative. Most users similarly upload small files for which a coverage report would not be useful.
