### ISSUE TITLE
Add a web API

### ISSUE THREAD

**Issue by robredpath** [open-contracting/cove-ocds#72]
Copied across from https://github.com/OpenDataServices/cove/issues/320 

The original issue has some discussion, but pertinent bits:

>It's certainly true that we don't intend CoVE / lib-cove-ocds to be used as part of the backend for a web site - it's definitely not fast enough. If there was a demand for this, we could probably concoct something - but I'd want to know more about exactly what was required. As it stands, I'm only aware of @patxiworks wanting to use CoVE in this way, and unfortunately we weren't able to support what he wanted to do.
>
> However, a web API to CoVE also has a role in publication systems, and potentially in data consumption applications, as part of automated processing, where response time isn't as important. Packaging up something that can be run as a 'black box' and handle requests for feedback on data that goes beyond simple validation can be useful.

and 

> I guess the use case for a web API is an implementer who is unable or unwilling to use lib-cove-ocds as a library. (Even if their system is implemented in another language, they can either bridge to Python, or shell out to the libcoveocds command.) Right now, the demand for that seems low, but the issue can certainly remain open.

**Comment by jpmckinney** [comment]
The jOCDS API is fast. Closing given low demand and available API.
