### ISSUE TITLE
coverage line in CI does nothing?

### ISSUE THREAD

**Issue by odscjames** [open-contracting/cove-ocds#79]
```
 Run coverage run --source cove_ocds,cove_project manage.py test
/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/cove/settings.py:31: UserWarning: SECRET_KEY should be added to Environment Variables. Random key will be used instead.
  warnings.warn('SECRET_KEY should be added to Environment Variables. Random key will be used instead.')

System check identified no issues (0 silenced).
----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```

When migrating from Travis to Github CI's, I left it in as I wasn't certain it does nothing, and if felt like we should check that. If it really does nothing, we can remove. I suspect coveralls data comes from the next test line anyway.

**Comment by jpmckinney** [comment]
That's because, although cove is a Django app, it uses pytest instead of unittest (which is what Django typically uses).

I'll just delete that line.
