### ISSUE TITLE
Validating record package shows incorrect release count

### ISSUE THREAD

**Issue by dwasyl** [open-contracting/cove-ocds#80]
When validating a record package with embedded releases the `Records Table` shows a `release count` of 0.

In the case of the sample data I was validating, it should have shown a `release count` of 3 - unless I'm entirely misinterpreting the column header.

Link to sample data validation here: https://standard.open-contracting.org/review/data/3a395812-d486-48b7-8789-d0d2e16e3651

**Comment by Bjwebb** [comment]
Yes, this is a bug. Looks like I moved some code over from the release package page, and was overzealous with my replacement of "releases" with "records".

**Comment by Bjwebb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Small bugs](https://trello.com/c/sDE1LIkp/97-small-bugs)

**Comment by Bjwebb** [comment]
This is fixed now.
