### ISSUE TITLE
Tests fail because httpstat.us/404 doesn't always return a 404 status code

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/cove-ocds#82]
http://httpstat.us/404 sometimes returns a different status code, such as 503 or 524, which is probably due to the request taking too long / not returning from the origin server, and Cloudflare making an error response.

[A GitHub search](https://github.com/search?q=org%3Aopen-contracting+httpstat.us&type=code) shows that we use this in this repo, and kingfisher-collect, so I've also [opened an issue there](https://github.com/open-contracting/kingfisher-collect/issues/505).

**Comment by jpmckinney** [comment]
I typically use https://pypi.org/project/pytest-vcr/ to avoid request errors (and make tests faster), but the commits look good, too.

**Comment by jpmckinney** [comment]
Closed by referencing commits. Tests take 12 mins, so pytest-vcr can probably make them faster. However, it's useful for the tests to run against live schema URLs, so just closing for now without creating a follow-up issue.
