### ISSUE TITLE
Stop HotJar

### ISSUE THREAD

**Issue by odscjames** [open-contracting/cove-ocds#83]
https://standard.open-contracting.org/review/terms/#privacy_notice says "The experiment runs from 4th March to 30th September 2020."

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Stop HotJar](https://trello.com/c/ZvotDNFW/96-stop-hotjar)

**Comment by Bjwebb** [comment]
@jpmckinney Should we disable the hotjar snippet tomorrow, as the text indicates?

**Comment by jpmckinney** [comment]
> @jpmckinney Should we disable the hotjar snippet tomorrow, as the text indicates?

Sure, we have enough data to analyze now.
