### ISSUE TITLE
Add call to action in the Validator example errors column

### ISSUE THREAD

**Issue by juanpane** [open-contracting/cove-ocds#94]
When there are errors in the validation, the error count column shows the errors for the row.
However, the number does not look like a link.
Perhaps a call to action is needed or format the number to look like a link

Example:  http://standard.open-contracting.org/validator/data/f7d35e4c-d3c8-4a3b-887c-539ceff7a491

**Comment by robredpath** [comment]
This request was moved to https://github.com/OpenDataServices/cove/issues/692 for a while.

**Comment by Bjwebb** [comment]
We're using bootstrap, so `glyphicon glyphicon-new-window` looks like a good candidate for this.

**Comment by Bjwebb** [comment]
Here's what I suggest this looks like:
![Screenshot from 2021-02-12 15-46-42](https://user-images.githubusercontent.com/634/107789561-a4cef980-6d49-11eb-893d-44edfb6e1827.png)
